### PR TITLE
Fixed incorrect URI encoding

### PR DESCRIPTION
**Pull request by MrHaCkEr**
Fix for issue #50 "ERR_UNESCAPED_CHARACTERS"

### CODE REVIEW

**Comment by gnuns** [comment]
Thank you! :D

**Comment by maksrise** [comment]
@gnuns, this PR breaks the service, issue #50 is incorrect, @MrHaCkEr didn't use encodeURIComponent:
```js
fetch(`https://api.allorigins.win/get?url=${encodeURIComponent('https://www.example.com/wow’s')}`);
```

**Comment by MrHaCkEr** [comment]
Don't these lines send requests to the url specified, so basically a `GET https://example.com/` ?

Except line 11, pretty sure that could be removed.

**Comment by maksrise** [comment]
@MrHaCkEr, [examples](https://github.com/gnuns/allOrigins#examples), the url can be with parameters, complex parameters:

`https://example.com/ajax?param1={"array":[1,2],"number":3,"string":"4"}&param2=value2`

MDN [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) description:

> Note that encodeURI() by itself cannot form proper HTTP GET and POST requests, such as for XMLHttpRequest, because "&", "+", and "=" are not encoded, which are treated as special characters in GET and POST requests. encodeURIComponent(), however, does encode these characters.

Your PR makes this:
```js
encodeURI(encodeURI(`https://api.allorigins.win/raw?url=${encodeURIComponent('https://example.com/ajax?param1={"array":[1,2],"number":3,"string":"4"}&param2=value2')}`))
```
Result:
`https://api.allorigins.win/raw?url=https%25253A%25252F%25252Fexample.com%25252Fajax%25253Fparam1%25253D%25257B%252522array%252522%25253A%25255B1%25252C2%25255D%25252C%252522number%252522%25253A3%25252C%252522string%252522%25253A%2525224%252522%25257D%252526param2%25253Dvalue2`

**Comment by maksrise** [comment]
@MrHaCkEr, [examples](https://github.com/gnuns/allOrigins#examples), the url can be with parameters, complex parameters:

`https://example.com/ajax?param1={"array":[1,2],"number":3,"string":"4"}&param2=value2`

MDN [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) description:

> Note that encodeURI() by itself cannot form proper HTTP GET and POST requests, such as for XMLHttpRequest, because "&", "+", and "=" are not encoded, which are treated as special characters in GET and POST requests. encodeURIComponent(), however, does encode these characters.

Your PR makes this:
```js
encodeURI(encodeURI(encodeURIComponent('https://example.com/ajax?param1={"array":[1,2],"number":3,"string":"4"}&param2=value2')))
```
Result:
`https%25253A%25252F%25252Fexample.com%25252Fajax%25253Fparam1%25253D%25257B%252522array%252522%25253A%25255B1%25252C2%25255D%25252C%252522number%252522%25253A3%25252C%252522string%252522%25253A%2525224%252522%25257D%252526param2%25253Dvalue2`

It must be:
`https%3A%2F%2Fexample.com%2Fajax%3Fparam1%3D%7B%22array%22%3A%5B1%2C2%5D%2C%22number%22%3A3%2C%22string%22%3A%224%22%7D%26param2%3Dvalue2`

**Comment by maksrise** [comment]
@MrHaCkEr, [examples](https://github.com/gnuns/allOrigins#examples), the url can be with parameters, complex parameters:

`https://example.com/ajax?param1={"array":[1,2],"number":3,"string":"4"}&param2=value2`

**Pull request merged**
